# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 kaayzouee
# Author: https://github.com/kaayzouee

# Generated by neodots-installer.
# Manual edits are valid, but the installer may replace this file.

{
  system = "x86_64-linux";

  neodots = {
    username = "kay";
    hostname = "nixos";
    homeDirectory = "/home/kay";

    personal = {
      enable = true;
    };

    persistence = {
      enable = false;
      path = "/persist";
    };
  };
}
